# Generated by Django 3.2 on 2024-06-01 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('trend1', models.CharField(max_length=255)),
                ('trend2', models.CharField(max_length=255)),
                ('trend3', models.CharField(max_length=255)),
                ('trend4', models.CharField(max_length=255)),
                ('trend5', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedData',
        ),
    ]
